version: '3.3'
services:
  chevereto-server:
    image: linuxserver/chevereto
    container_name: schevereto
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    environment:
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
      DB_HOST: chevereto_db
      DB_PORT: 3306
      DB_NAME: picbed
      DB_USER: picbed
      DB_PASS: picbed
    volumes:
      - ./data:/data
      - ./config:/config
    ports:
      - 7777:80
    depends_on:
      - chevereto_db
  chevereto_db:
    image: mysql:5.7
    container_name: chevereto_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: picbed
      MYSQL_DATABASE: picbed
      MYSQL_USER: picbed
      MYSQL_PASSWORD: picbed
    volumes:
      - ./db:/var/lib/mysql