/**
 * 后端/平台技术领域侧边栏配置
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  backendSidebar: [
    {
      type: 'category',
      label: '平台技术',
      link: {
        type: 'generated-index',
        title: 'Platform Engineering',
        description: '探索 Java、Spring、微服务架构、系统设计等平台技术',
        slug: '/category/platform-engineering',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    },
  ],
};

module.exports = sidebars;
