/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // AI & LLM 侧边栏
  aiSidebar: [
    {
      type: 'category',
      label: 'AI & LLM',
      link: {
        type: 'generated-index',
        title: 'AI & LLM',
        description: '人工智能与大语言模型技术探索',
        slug: '/ai-llm',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-llm',
        },
      ],
    },
  ],

  // Infrastructure 侧边栏
  infraSidebar: [
    {
      type: 'category',
      label: 'Infrastructure',
      link: {
        type: 'generated-index',
        title: 'Infrastructure',
        description: '基础设施与云原生技术',
        slug: '/infrastructure',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'infrastructure',
        },
      ],
    },
  ],

  // Backend 侧边栏
  backendSidebar: [
    {
      type: 'category',
      label: 'Backend',
      link: {
        type: 'generated-index',
        title: 'Backend Development',
        description: '后端开发技术与实践',
        slug: '/backend',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend',
        },
      ],
    },
  ],
};

module.exports = sidebars;
