/**
 * AI Infra 领域侧边栏配置
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aiinfraSidebar: [
    {
      type: 'category',
      label: 'AI Infra',
      link: {
        type: 'generated-index',
        title: 'AI Infrastructure',
        description: '探索大语言模型、RAG 系统、向量数据库、推理加速等 AI 基础设施技术',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    },
  ],
};

module.exports = sidebars;
